import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { ThemeContext } from "../context/Context";
import Footer from "../Components/Layout/Footer";
import TopBar from "../Components/Layout/TopBar";
import Category from "../Components/HomePage/Category";
import ItemCard from "../Components/ItemsPage/PlaystationCard";
import Playstation from "../Assets/banners/Accessory2.jpg";

const Accessory = () => {
  const [theme, setTheme] = useState("light");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stateString = JSON.stringify(theme);
      window.localStorage.setItem("theme", stateString);
    }
  }, [theme]);

  useEffect(() => {
    if (typeof window !== "undefined" && window.localStorage) {
      const getString = window.localStorage.getItem("theme");
      const state = JSON.parse(getString);
      setTheme(state);
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme((curr) => (curr === "light" ? "dark" : "light"));
  };

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      <div id={theme}>
        <Head>
          <title>Swift Games | Accessories</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="playstation-page">
          <TopBar />
          <h1>Gaming Accessories</h1>
          <Image
            width="auto"
            height="auto"
            src={Playstation}
            alt="image description"
          />
          <ItemCard />
          <Category />
          <Footer />
        </div>
      </div>
    </ThemeContext.Provider>
  );
};

export default Accessory;
