import React, {useState} from 'react'
import Head from 'next/head'
import { ThemeContext } from "../context/Context";
import TopBar from '../Components/Layout/TopBar'
import Footer from '../Components/Layout/Footer'
import DetailsPage from '../Components/DetailsPage/DetailsPage'

const Details = () => {

  const storage = typeof window !== "undefined" ? localStorage.theme: 'light'
  const [theme, setTheme] = useState(storage);

  useEffect(() => {
    if (localStorage.getItem('theme') !== theme) {
      const setString = JSON.stringify(theme);
      window.localStorage.setItem("theme", setString);
    }
  }, [ theme ]);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const getString = window.localStorage.getItem("theme");
      const state = JSON.parse(getString);
      setTheme(state)
      console.log(state)
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme((curr) => (curr === "light" ? "dark" : "light"));
  };

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      <div id={theme}>
    <Head>
        <title>Swift Games | Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <TopBar/>
      <div className='item-details'>
        <DetailsPage/>
        <Footer/>
      </div>
    </div>
    </ThemeContext.Provider>
  )
}

export default Details