import axios from "axios";
import Head from "next/head";
import TopBar from "../Components/Layout/TopBar";
import Footer from "../Components/Layout/Footer";
import { getGames } from "../lib/Providers/Games";
import { getBanner } from "../lib/Providers/Banner";
import { getDiscounts } from "../lib/Providers/Discount";
import {
  GameContext,
  BannerContext,
  AccessoryContext,
} from "../context/Context";
import Category from "../Components/HomePage/Category";
import GamesCard from "../Components/HomePage/games/GamesCard";
import Carousel from "../Components/HomePage/Carousel/Carousel";
import Discounts from "../Components/HomePage/Discounts/Discounts";
import { getHomeAccessories } from "../lib/Providers/Accessories";
import Accessories from "../Components/HomePage/Accessories/Accessories";

export default function Home({ res, banner, discount, accessories }) {
  return (
    <>
      <Head>
        <title>Swift Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <BannerContext.Provider value={{ banner }}>
        <Carousel />
      </BannerContext.Provider>

      <Category />

      <GameContext.Provider value={{ discount }}>
        <Discounts />
      </GameContext.Provider>

      <GameContext.Provider value={{ res }}>
        <GamesCard />
      </GameContext.Provider>

      <AccessoryContext.Provider value={{ accessories }}>
        <Accessories />
      </AccessoryContext.Provider>

      <Footer />
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await getGames();
  const banner = await getBanner();
  const discount = await getDiscounts();
  const accessories = await getHomeAccessories();
  return {
    props: { res, banner, discount, accessories },
  };
};
