import Head from "next/head";
import Image from "next/image";
import { React, useState, useEffect } from "react";
import { ThreeCircles } from "react-loader-spinner";
import Footer from '../Components/Layout/Footer'
import TopBar from "../Components/Layout/TopBar";
import { GameContext } from "../context/Context";
import { ThemeContext } from "../context/Context";
import { getPs4Games } from "../lib/Providers/Games";
import Category from "../Components/HomePage/Category";
import Playstation from '../Assets/banners/playstation2.jpg'
import ItemCard from "../Components/ItemsPage/PlaystationCard";

const PlayStation = ({res}) => {

  const [theme, setTheme] = useState("light");
  const stateString = JSON.stringify(theme);
  localStorage.setItem('theme', stateString);

  const getString = localStorage.getItem('theme');
const state = JSON.parse(getString);

  const toggleTheme = () => {
    setTheme((curr) => (curr === "light" ? "dark" : "light"));
  };

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, []);

    return () => {
      clearTimeout(timer);
    }
  }, [res]);

  if (loading) {
    return (
      <div className="loading-screen">
        <ThreeCircles
          height="100"
          width="100"
          color="blue"
          wrapperStyle={{}}
          wrapperClass=""
          visible={true}
          ariaLabel="three-circles-rotating"
          outerCircleColor=""
          innerCircleColor=""
          middleCircleColor=""
        />
      </div>
    );
  }

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      <div id={theme}>
      <Head>
        <title>Swift Games | Playstation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="playstation-page">
        <TopBar />
        <h1>PlayStation Games</h1>
        <Image
        src={Playstation}
        />
        <GameContext.Provider value={{ res }}>
        <ItemCard />
        </GameContext.Provider>
        <Category />
        <Footer/>
      </div>
    </div>
    </ThemeContext.Provider>
  );
};

export const getServerSideProps = async () => {
  const res = await getPs4Games();
  return {
    props: { res },
  };
};

export default PlayStation;
