import React from "react";
import Head from "next/head";
import Image from "next/image";
import Footer from '../Components/Layout/Footer'
import TopBar from "../Components/Layout/TopBar";
import { GameContext } from "../context/Context";
import { getPs4Games } from "../lib/Providers/Games";
import Category from "../Components/HomePage/Category";
import Playstation from '../Assets/banners/playstation2.jpg'
import ItemCard from "../Components/ItemsPage/PlaystationCard";

const PlayStation = ({res}) => {
  return (
    <>
      <Head>
        <title>Swift Games | Playstation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="playstation-page">
        <TopBar />
        <h1>PlayStation Games</h1>
        <Image
        src={Playstation}
        />
        <GameContext.Provider value={{ res }}>
        <ItemCard />
        </GameContext.Provider>
        <Category />
        <Footer/>
      </div>
    </>
  );
};

export const getServerSideProps = async () => {
  const res = await getPs4Games();
  return {
    props: { res },
  };
};

export default PlayStation;
