import React from "react";
import Head from "next/head";
import Image from "next/image";
import Footer from '../Components/Layout/Footer'
import TopBar from "../Components/Layout/TopBar";
import Category from "../Components/HomePage/Category";
import ItemCard from "../Components/ItemsPage/PlaystationCard";
import Playstation from '../Assets/banners/nitendo.png'

const Switch = () => {
  return (
    <>
      <Head>
        <title>Swift Games | Nietendo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="playstation-page">
        <TopBar />
        <h1>Switch Games</h1>
        <Image
        src={Playstation}
        />
        <ItemCard />
        <Category />
        <Footer/>
      </div>
    </>
  );
};

export default Switch;
