import React from "react";
import Head from "next/head";
import Image from "next/image";
import Footer from '../Components/Layout/Footer'
import TopBar from "../Components/Layout/TopBar";
import { GameContext } from "../context/Context";
import Category from "../Components/HomePage/Category";
import Playstation from '../Assets/banners/xbox.jpg'
import { getXboxGames } from "../lib/Providers/Games";
import ItemCard from "../Components/ItemsPage/XboxCard";

const XBox = ( {res} ) => {
  return (
    <>
      <Head>
        <title>Swift Games | X Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="playstation-page">
        <TopBar />
        <h1>X BOX Games</h1>
        <Image
        src={Playstation}
        />
        <GameContext.Provider value={{ res }}>
        <ItemCard />
        </GameContext.Provider>
        <Category />
        <Footer/>
      </div>
    </>
  );
};

export const getServerSideProps = async () => {
  const res = await getXboxGames();
  console.log(res)
  return {
    props: { res },
  };
};

export default XBox;
